INSERT INTO `items` (`name`, `label`, `limit`, `rare`, `can_remove`, `weight`) VALUES
  ('a_c_boar_meat', 'Boar Meat', 15, 0, 1, 3),
  ('a_c_boar_pelt_bad', 'Bad Boar Pelt', 5, 0, 1, 2),
  ('a_c_boar_pelt_good', 'Good Boar Pelt', 5, 0, 1, 2),
  ('a_c_boar_pelt_rare', 'Rare Boar Pelt', 5, 0, 1, 2),
  ('a_c_chickenhawk_meat', 'Chicken Hawk Meat', 15, 0, 1, 1),
  ('a_c_chickenhawk_pelt_bad', 'Bad Chicken Hawk Feather', 5, 0, 1, 1),
  ('a_c_chickenhawk_pelt_good', 'Good Chicken Hawk Feather', 5, 0, 1, 1),
  ('a_c_chickenhawk_pelt_rare', 'Rare Chicken Hawk Feather', 5, 0, 1, 1),
  ('a_c_cormorant_meat', 'Cormorant Meat', 15, 0, 1, 1),
  ('a_c_cormorant_pelt_bad', 'Bad Cormorant Feather', 5, 0, 1, 1),
  ('a_c_cormorant_pelt_good', 'Good Cormorant Feather', 5, 0, 1, 1),
  ('a_c_cormorant_pelt_rare', 'Rare Cormorant Feather', 5, 0, 1, 1),
  ('a_c_coyote_meat', 'Coyote Meat', 15, 0, 1, 3),
  ('a_c_coyote_pelt_bad', 'Bad Coyote Pelt', 5, 0, 1, 2),
  ('a_c_coyote_pelt_good', 'Good Coyote Pelt', 5, 0, 1, 2),
  ('a_c_coyote_pelt_rare', 'Rare Coyote Pelt', 5, 0, 1, 2),
  ('a_c_crow_meat', 'Crow Meat', 15, 0, 1, 1),
  ('a_c_crow_pelt_bad', 'Bad Crow Feather', 5, 0, 1, 1),
  ('a_c_crow_pelt_good', 'Good Crow Feather', 5, 0, 1, 1),
  ('a_c_crow_pelt_rare', 'Rare Crow Feather', 5, 0, 1, 1),
  ('a_c_deer_meat', 'Deer Meat', 15, 0, 1, 3),
  ('a_c_deer_pelt_bad', 'Bad Deer Pelt', 5, 0, 1, 2),
  ('a_c_deer_pelt_good', 'Good Deer Pelt', 5, 0, 1, 2),
  ('a_c_deer_pelt_rare', 'Rare Deer Pelt', 5, 0, 1, 2),
  ('a_c_mtlion_meat', 'Mountain Lion Meat', 15, 0, 1, 3),
  ('a_c_mtlion_pelt_bad', 'Bad Mountain Lion Pelt', 5, 0, 1, 2),
  ('a_c_mtlion_pelt_good', 'Good Mountain Lion Pelt', 5, 0, 1, 2),
  ('a_c_mtlion_pelt_rare', 'Rare Mountain Lion Pelt', 5, 0, 1, 2),
  ('a_c_pigeon_meat', 'Pigeon Meat', 15, 0, 1, 1),
  ('a_c_pigeon_pelt_bad', 'Bad Pigeon Feather', 5, 0, 1, 1),
  ('a_c_pigeon_pelt_good', 'Good Pigeon Feather', 5, 0, 1, 1),
  ('a_c_pigeon_pelt_rare', 'Rare Pigeon Feather', 5, 0, 1, 1),
  ('a_c_rabbit_meat', 'Rabbit Meat', 15, 0, 1, 1),
  ('a_c_rabbit_pelt_bad', 'Bad Rabbit Pelt', 5, 0, 1, 1),
  ('a_c_rabbit_pelt_good', 'Good Rabbit Pelt', 5, 0, 1, 1),
  ('a_c_rabbit_pelt_rare', 'Rare Rabbit Pelt', 5, 0, 1, 1),
  ('a_c_rat_meat', 'Rat Meat', 15, 0, 1, 1),
  ('a_c_rat_pelt_bad', 'Bad Rat Pelt', 5, 0, 1, 1),
  ('a_c_rat_pelt_good', 'Good Rat Pelt', 5, 0, 1, 1),
  ('a_c_rat_pelt_rare', 'Rare Rat Pelt', 5, 0, 1, 1),
  ('a_c_seagull_meat', 'Seagull Meat', 15, 0, 1, 1),
  ('a_c_seagull_pelt_bad', 'Bad Seagull Feather', 5, 0, 1, 1),
  ('a_c_seagull_pelt_good', 'Good Seagull Feather', 5, 0, 1, 1),
  ('a_c_seagull_pelt_rare', 'Rare Seagull Feather', 5, 0, 1, 1),
  ('a_c_cat_01_meat', 'Cat Meat', 15, 0, 1, 1),
  ('a_c_cat_01_pelt_bad', 'Bad Cat Pelt', 5, 0, 1, 1),
  ('a_c_cat_01_pelt_good', 'Good Cat Pelt', 5, 0, 1, 1),
  ('a_c_cat_01_pelt_rare', 'Rare Cat Pelt', 5, 0, 1, 1),
  ('a_c_poodle_meat', 'Poodle Meat', 15, 0, 1, 1),
  ('a_c_poodle_pelt_bad', 'Bad Poodle Pelt', 5, 0, 1, 1),
  ('a_c_poodle_pelt_good', 'Good Poodle Pelt', 5, 0, 1, 1),
  ('a_c_poodle_pelt_rare', 'Rare Poodle Pelt', 5, 0, 1, 1),
  ('a_c_pug_meat', 'Pug Meat', 15, 0, 1, 1),
  ('a_c_pug_pelt_bad', 'Bad Pug Pelt', 5, 0, 1, 1),
  ('a_c_pug_pelt_good', 'Good Pug Pelt', 5, 0, 1, 1),
  ('a_c_pug_pelt_rare', 'Rare Pug Pelt', 5, 0, 1, 1),
  ('a_c_westy_meat', 'Westy Meat', 15, 0, 1, 1),
  ('a_c_westy_pelt_bad', 'Bad Westy Pelt', 5, 0, 1, 1),
  ('a_c_westy_pelt_good', 'Good Westy Pelt', 5, 0, 1, 1),
  ('a_c_westy_pelt_rare', 'Rare Westy Pelt', 5, 0, 1, 1),
  ('a_c_chop_meat', 'Rottweiler Meat', 15, 0, 1, 1),
  ('a_c_chop_pelt_bad', 'Bad Rottweiler Pelt', 5, 0, 1, 1),
  ('a_c_chop_pelt_good', 'Good Rottweiler Pelt', 5, 0, 1, 1),
  ('a_c_chop_pelt_rare', 'Rare Rottweiler Pelt', 5, 0, 1, 1),
  ('a_c_husky_meat', 'Husky Meat', 15, 0, 1, 1),
  ('a_c_husky_pelt_bad', 'Bad Husky Pelt', 5, 0, 1, 1),
  ('a_c_husky_pelt_good', 'Good Husky Pelt', 5, 0, 1, 1),
  ('a_c_husky_pelt_rare', 'Rare Husky Pelt', 5, 0, 1, 1),
  ('a_c_retriever_meat', 'Retriever Meat', 15, 0, 1, 1),
  ('a_c_retriever_pelt_bad', 'Bad Retriever Pelt', 5, 0, 1, 1),
  ('a_c_retriever_pelt_good', 'Good Retriever Pelt', 5, 0, 1, 1),
  ('a_c_retriever_pelt_rare', 'Rare Retriever Pelt', 5, 0, 1, 1),
  ('a_c_shepherd_meat', 'German Shephard Meat', 15, 0, 1, 1),
  ('a_c_shepherd_pelt_bad', 'Bad German Shephard Pelt', 5, 0, 1, 1),
  ('a_c_shepherd_pelt_good', 'Good German Shephard Pelt', 5, 0, 1, 1),
  ('a_c_shepherd_pelt_rare', 'Rare German Shephard Pelt', 5, 0, 1, 1)
;